### ISSUE TITLE
Make the default back-end that the front-end connects to the staging server

### ISSUE THREAD

**Issue by King-Mob** [Wobbly-App/wobbly-frontend#159]
For ease of first developing, perhaps the first thing that the front-end connects to should be the staging server, and then connecting to your local back-end should be part of the instructions in the back-end repo.

**Comment by chrisdevereux** [comment]
we need a better general approach to managing environments. Generally, I like the approach of having multiple app.json files and selecting between them with a flag passed to expo. We can then pass configuration through via the `expo.constants` object

**Comment by chrisdevereux** [comment]
I hijacked the __DEV__ variable to select them, but this has annoying side effects like not showing errors when running in --no-dev mode
