### ISSUE TITLE
Change "create thread" icon

### ISSUE THREAD

**Issue by brortao** [Wobbly-App/wobbly-frontend#235]
right now, it looks like it's used to edit the group title!

**Comment by King-Mob** [comment]
Myself and @an-k45 talked this through very briefly today, and the solution we came to was changing the icon and moving it to the bottom right corner of the screen, being on top of any threads that were there if there were more threads than can appear on the screen.

But this did highlight the need for a mock-up that we agree on before we implement a change to the UI

**Comment by King-Mob** [comment]
![wobbly screenshot](https://user-images.githubusercontent.com/38507954/58962561-6b3ba200-87a3-11e9-9097-b87216b8a6bf.png)

**Comment by brortao** [comment]
yeah, this change makes sense to me

fyi i have an in-progress branch where i’m changing out navigation a bit. instead of opening to a list of groups, you open to the previous groups. there are bottom tabs for:
* chats
* polls
* group info

to switch to another group, you swipe from the left side of the screen or press a hamburger menu in the top left (like in discord or slack).

this is because
1) most people will probably just be in one group so it seems silly to always start at a group overview
2) we probably want polls to be in their own tab such that they’re easily distinguished from chats. this tab doesn’t make sense with our current nav setup.

— Tao

**Comment by brortao** [comment]
@King-Mob 	and @an-k45 	do you think #288 resolves this issue?

**Comment by King-Mob** [comment]
The issue for me was that the "new thread" button was reading as the "edit group name" button. I think it's now less likely to be read as that, but it's still possible. Maybe users won't care, maybe if it's a different colour it'll be different.

I think it's a low priority, almost non-issue until it comes up again in user testing.

**Comment by King-Mob** [comment]
So, happy to close

**Comment by an-k45** [comment]
I'm with @King-Mob here, the pull request you've made makes a working fix and we can always come back to design specifics, so I'm good with a close for now.
