### ISSUE TITLE
Settings page

### ISSUE THREAD

**Issue by King-Mob** [Wobbly-App/wobbly-frontend#24]

**Comment by apodiptych** [comment]
From the account screen, we'd like a settings icon in the top right of the statusbar (a gear icon). This should take you to a new screen in the[ `AccountStack`](https://github.com/Wobbly-App/wobbly-frontend/blob/develop/src/AppNavigation.tsx#L18).

This is where we'll have a list of our settings long-term. For now, perhaps the only entry on the list will be #8.
