### ISSUE TITLE
Document repository for groups

### ISSUE THREAD

**Issue by King-Mob** [Wobbly-App/wobbly-frontend#31]
a list of links to documents that groups have made and are relying on

**Comment by brortao** [comment]
For v0.1.0-alpha, here's how this could work:

In a group, members can either create a new thread or a "wiki post". Wiki posts might look like threads, but cannot have replies and any member of the group can edit it.

Creating a wiki post can be done in one of two ways:
* (a) a single "create thread" screen with a checkbox to make it "wiki-style"
* (b) when clicking the "+" button in a group, a popup where members can select thread or wiki post

**Comment by brortao** [comment]
Another option is to explicitly have a separate forum and wiki for each group (i.e. in each group, there are two tabs at the bottom). I don't hate this idea. It'd encourage a 2-speed stack (or maybe 2.5 speed if we make forum threads feel fast and semi chat-like).

**Comment by brortao** [comment]
Discussion in the forum: https://discourse.wobbly.app/t/document-repository-wikis/184

**Comment by brortao** [comment]
Closing this out as we have thread pinning.

Can reopen if needed.
