### ISSUE TITLE
Setup tests

### ISSUE THREAD

**Issue by brortao** [Wobbly-App/wobbly-frontend#67]
I tried making typesript + jest play nice, but ran into a few issues with our app (IIRC, things to do with react-navigation). At some point soon we should actually set up testing.

**Comment by chrisdevereux** [comment]
[  ] Setup storybook / react-native-dom
[  ] Add stories for existing components
[  ] Setup snapshot tests
[  ] Add unit tests for services
[  ] Repeatedly poke .travis.yml with a stick
[  ] Document testing guidelines
